changed all alerts to antD alerts
Lambda-School-Labs/human-rights-first-asylum-fe-a pull request #250
Opened 2021-06-09 23:27 UTC by natepace

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] No duplicate code left within changed files
- [ ] Size of pull request kept to a minimum
- [ ] Pull request description clearly describes changes made & motivations for said changes

2021-06-10 23:16 UTC, Poonchy requested changes
Just merge the imports. The rest of the code works fine locally.

2021-06-14 14:32 UTC, Poonchy approved these changes

2021-06-14 17:47 UTC, taylorfriesen6 commented on .env.sample
> -REACT_APP_CLIENT_ID=getThisFromCredentialsDoc
Do not delete .env.sample

2021-06-14 18:11 UTC, taylorfriesen6 commented
Other than that, everything else seems good to me, and works on my local machine.

2021-06-15 14:09 UTC, nicholasbus requested changes
Everything is good, just remove the `.env.sample` deletion from the PR

2021-06-15 14:09 UTC, nicholasbus commented on .env.sample
> -REACT_APP_CLIENT_ID=getThisFromCredentialsDoc
remove this file from the PR please

2021-06-15 19:53 UTC, taylorfriesen6 approved these changes

2021-06-15 19:57 UTC, merged