Feature/native notifications
Lambda-School-Labs/human-rights-first-asylum-fe-a pull request #254
Opened 2021-06-11 21:22 UTC by lindellcarternyc

## Description

This pull request adds a native dropdown menu for notifications. This is a skeleton that needs improvement, but it includes a system for callbacks to capture user interaction with the system.

## Type of change
- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have removed unnecessary comments/console logs from my code
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] No duplicate code left within changed files
- [ ] Size of pull request kept to a minimum
- [ ] Pull request description clearly describes changes made & motivations for said changes

## TODO
- [ ] Pull real data from backend / Context API
- [ ] Integrate styling using LESS instead of inline styles

2021-06-11 21:31 UTC, Randyo28 approved these changes
Nice Lindell this looks really good for the skeleton code for notifications

2021-06-14 17:17 UTC, fullstackcaveman requested changes
Great work so far.
Just a few code issues to double-check.

Also, please remove the package-lock.json from the PR. <--- Requested Change

2021-06-14 17:17 UTC, fullstackcaveman commented on src/components/pages/Home/MainHeader.js
> +const MOCK_NOTIFICATIONS = [
Is this temporary?
I assume it is since it has an unconventional name. 
Perhaps add a comment here indicating its use if so.

2021-06-14 17:17 UTC, fullstackcaveman commented on src/components/pages/Home/MainHeader.js
>            <ul className="accounts" onClick={e => e.preventDefault()}>
The event indicator here doesn't match the rest of the included code. ie:   e or evt

2021-06-14 17:17 UTC, fullstackcaveman commented on src/components/pages/Home/Notifications.js
> +  const handleClick = key => {
Looks like you'll need to pass in the event here as well.
`const handleClick = (evt, key) => {`

2021-06-14 17:17 UTC, fullstackcaveman commented on src/components/pages/Home/Notifications.js
> +    return evt => {
I was curious about the return here.
Wouldn't it be cleaner as:
```const handleClick = (evt, key) => {
       evt.preventDefault()

       if (key === 'view') {
         return onClickView(notification.id);
       } else if (key === 'dismiss') {
         return onClickDismiss(notification.id);
       }
```

2021-06-14 17:17 UTC, fullstackcaveman commented on src/components/pages/Home/Notifications.js
> +          onClick={handleClick('view')}
Since you are calling a method and passing a prop:
`onClick={evt => handleClick('view')}`

2021-06-14 17:17 UTC, fullstackcaveman commented on src/components/pages/Home/Notifications.js
> +        <a href="#" onClick={handleClick('dismiss')}>
Since you are calling a method and passing a prop:
`onClick={evt => handleClick('dismiss')}`

2021-06-16 22:41 UTC, fullstackcaveman approved these changes
package-lock has a merge conflict.

2021-06-17 13:54 UTC, merged